### PR TITLE
F-476: add marketplace app resource

### LINKED ISSUE #476: Add `opennebula_marketplace_app` resource and data source
### Description

Along side of `opennebula_marketplace` resource and data source (#414), we should add an `opennebula_marketplace_app` resource and data source to create apps within the created marketplace.

We might be able to retrieve data source by `name` or `id`.

### New or affected resources and data sources

`opennebula_marketplace`

### Potential terraform configuration

```HCL
resource "opennebula_marketplace_app" "my_app" {
  name = "My App"
  description = "This is my amazing app !"
  version = "0.2"
  image = opennebula_image.my_image.id
  marketplace = opennebula_marketplace.my_marketplace.id
  vm_template = "..."
  app_template = "..."
}
```

### References

#414

### PR DESCRIPTION
**Pull request by treywelsh**
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for PR followers and do not help prioritize the request

### Description

Add marketplace appliance resource and datasource

### References

close #476 

### New or Affected Resource(s)

- opennebula_marketplace_app
- data_opennebula_marketplace_app

### Checklist

- [ ] I have created an issue and I have mentioned it in `References`
- [ ] My code follows the style guidelines of this project (use `go fmt`)
- [ ] My changes generate no new warnings or errors
- [ ] I have updated the unit tests and they pass succesfuly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation (if needed)
- [ ] I have updated the changelog file

### CODE REVIEW

**Comment by treywelsh** [comment]
TODO: add tests, doc, changelog
Note: in the appliance template there's a TAGS section:```TAGS><![CDATA[alpine, kubernetes, service, vnf]]></TAGS>```
This could be misleading, as said in this issue: https://github.com/OpenNebula/terraform-provider-opennebula/issues/478

**Comment by treywelsh** [comment]
I have a small problem: I tried to create an app with this TF:
```
resource "opennebula_marketplace_app" "example" {
  name = "test"
  market_id = "122"
  type = "IMAGE"
  description = "this is an app"
  publisher = "toto"
  version = "0.1.0"
  vmtemplate64 = "REVTQz0idGhpcyBpcyBhIHZtIHRlbXBsYXRlIgo="
  apptemplate64 = "REVTQz0idGhpcyBpcyBhbiBhcHAgdGVtcGxhdGUiCg=="

  tags = {
    custom1 = "value1"
  }
}
```

It's surely broken, however the create method returns an error and doesn't returns an ID but the app is created in OpenNebula and has ERROR state.
The provider should be able to delete the application but is not without having the app ID.
The XML-RPC method has a return field either used to return an ID, or the error string, it's probably why we don't get an ID but an error message instead. Should the resource be created then ?

To fix this and be able to retrieve the ID, we could add to the appliance a custom field containing an ID string used to identify the resource created, the provider could juste remove this ID later. [I already did something like this for the virtual router instances](https://github.com/OpenNebula/terraform-provider-opennebula/blob/1c7b694f81fd49735e78da18c4894e64e65498e6/opennebula/resource_opennebula_virtual_router_instance.go#L138)

**Comment by treywelsh** [comment]
Depends on https://github.com/OpenNebula/one/pull/6312

**Comment by treywelsh** [comment]
5.12 release tests fails because in the acceptance test config I'm testing an appliance type that wasn't supported.
I'm trying to make the acceptance tests for 5.12 to ignore this error to make them pass

**Comment by treywelsh** [comment]
Acceptances test are failing with OpenNebula 5.12: `Marketplace app type not supported` 
The acceptance test is currently trying to use `VMTEMPLATE` as appliance type

**Review by frousselet — APPROVED** [review]

**Pull request merged**
