### PR TITLE
Fix VN test for OpenNebula 6.4

### PR DESCRIPTION
**Pull request by paczerny**
OpenNebula release 6.4 introduce new VN STATE. Operations `onevnet create` and `onevnet delete` are asynchronous.
This breaks the `testAccCheckVirtualNetworkDestroy`

This commit waits for the VN to be deleted.

### CODE REVIEW

**Comment by treywelsh** [comment]
Is it possible for the delete operation to fail (failure states ... ) ? I didn't find the informations in official documentation. The information should be available in changes of a PR of the one repository but it would be nice to have the information here.

If yes I think  we should also add the same kind of polling in the Delete method of the virtual network to ensure that the provider understand if the deletion is effective.

At first glance, even if this change is announced to be for One 6.4, the implementation use RPC methods already implemented in ONE 5.12 and 6.2 (virtual network info call), so this shouldn't break compatibility with older versions.

**Comment by paczerny** [comment]
The Delete operation and also the Create operation may fail (VN->STATE is ERROR), or can get stuck (VN->STATE is LOCK_DELETE or LOCK_CREATE). [Documentation to new VN state in 6.4](https://docs.opennebula.io/6.3/management_and_operations/network_management/manage_vnets.html#states-and-life-cycle).

Yes, this change in tests is compatible with older versions. In theory similar polling is needed for VN create, but I haven't noticed any issue with the create in the tests.

If we add this polling to Create and Delete method, then I think we don't need to modify the tests. But the polling in the Create would need a 6.4 interface to check the new attribute VN->STATE == READY

**Comment by treywelsh** [comment]
Thanks for the additional informations

There is an RPC method to detect the OpenNebula version ( [see here](https://docs.opennebula.io/5.12/integration/system_interfaces/api.html#one-system-version) ).
We could use this method to introduce release conditional code parts that we could remove later, i.e. when older releases than 6.4 are not maintained anymore.

I'm not sure that we should introduce ONE release dependant code, and it seems that 6.4 is not stable for now.
What's are your point of view @paczerny and @frousselet ?

**Comment by frousselet** [comment]
> We could use this method to introduce release conditional code parts that we could remove later, i.e. when older releases than 6.4 are not maintained anymore.

Yes. I am just not sure how to deal with the user documentation in this case...

> I'm not sure that we should introduce ONE release dependant code, **and it seems that 6.4 is not stable for now**.

The stable Provider should only support stable ONE releases (currently `5.12.0.4`, `5.12.12`, `6.2.0` and `6.2.2`).

**Comment by paczerny** [comment]
The 6.4 version will be released this week and will be an LTS version, whose release will deprecate 5.12 and 6.2 series. So we can wait with these changes until 6.4 release

**Comment by treywelsh** [comment]
If we are able to test that we use a 6.4 version or higher reliably this should be invisible for the user so we shouldn't have to document this ?
However, for now the CI only test 5.12 and 6.2 ONE releases, we may want to add a 6.4 test pipeline to be sure of our changes

**Review by frousselet — APPROVED** [review]

**Pull request merged**
