### PR TITLE
F-269: update sdk2 code

### LINKED ISSUE #267: Depreciate `timeout` attributes from `opennebula_virtual_machine` and `opennebula_image` and use built-in Terraform SDK features
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In some resources there is a `timeout` attribute. This should be deprecated to use SDK tools.

### New or Affected Resource(s)

- opennebula_virtual_machine
- opennebula_image

### References

See `Timeout` schema field: See schema field: https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Resource

### LINKED ISSUE #269: improve code to match SDK v2 standards
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Some weeks ago we migrated this provider to work on top of the sdk v2. It works fine but now there is a bunch of deprecated methods:

- CRUD methods all use a context for now and doesn't returns an error anymore but a slice of `Diagnostics`
- GetOkExists is deprecated

I'll need to work a bit on it to add a more detailed list of changes to do.

### New or Affected Resource(s)

All resources will be affected, but it will probably be invisible changes to the user.

### References

- #161
- https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide

### PR DESCRIPTION
**Pull request by treywelsh**
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for PR followers and do not help prioritize the request

### Description

This refactor resources and datasources to replace deprecated methods and use new SDK tools.

### References

Close #269
Close #267 

### New or Affected Resource(s)

All resources and datasources are modified

### Checklist

- [x] I have created an issue and I have mentioned it in `References`
- [x] My code follows the style guidelines of this project (use `go fmt`)
- [x] My changes generate no new warnings or errors
- [x] I have updated the unit tests and they pass succesfuly
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the documentation (if needed)
- [x] I have updated the changelog file

### CODE REVIEW

**Comment by treywelsh** [comment]
CI is failing on a virtual network acceptance test step that tries to test an error case.
This step test try to test for an expected error to occur, based on error message string matching...
However, with diagnostics structures replacing errors in this PR, now it seems that errors messages are more verbose than before and potentially not formatted in the same way (the expected error message seem to be splitted on two lines now....) :
```
=== RUN   TestAccVirtualNetwork
    resource_opennebula_virtual_network_test.go:20: Step 4/4, expected an error with pattern, no match on: Error running apply: exit status 1
        Error: Failed to retrieve informations
          with opennebula_virtual_network.non-existing-reservation,
          on terraform_plugin_test.tf line 2, in resource "opennebula_virtual_network" "non-existing-reservation":
           2: resource "opennebula_virtual_network" "non-existing-reservation" {
        OpenNebula error [NO_EXISTS]: [one.vn.info] Error getting virtual network
        [25].
```
I would prefer to avoid error message matching as much as I can but infortunately SDK v2 doesn't seems to provide an other way to do.

**Comment by treywelsh** [comment]
See issue #278 for the code scanning error.

**Comment by treywelsh** [comment]
I didn't remove the `GetOkExists` call because there is no alternatives in the SDK.

At least we could replace the fields type on which they are used from TypeInt to TypeString, and test the string len to ensure that the user passed a value...

**Comment by treywelsh** [comment]
By the way I took a small liberty in removing a bit of ACL dead code that I put in a separated commit.

**Review by frousselet — APPROVED** [review]

**Review by frousselet — CHANGES_REQUESTED** [review]
Missing Changelog

**Review by frousselet — APPROVED** [review]

**Pull request merged**
