### PR TITLE
B-312: vm import: read section when not configured

### LINKED ISSUE #312: [0.5.1] import and refresh populate fields with invalid "null" value
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### Affected Resource(s)

- opennebula_virtual_machine

### Expected Behavior

`terraform import` and `terraform refresh` import values with a meaningful default

### Actual Behavior

`terraform import` and `terraform refresh` set a lot of values to `null`, causing problem during operation. Examples:

during refresh:

* `template_id: null` should be `-1`
* `nic_template: null` should be `[]`
* `disk_template: null` should be `[]`

during import:

* `timeout: null` should be a reasonable numerical value (gets implicitly cast to 0, which means e.g. `terraform destroy` cannot succeed).

Alternatively, the module should handle null values gracefully, but it stands to reason that whatever is in the state should be non-ambiguous.

### Steps to Reproduce

1. Run `terraform refresh` on an inventory created with an older version
2. Run `terraform import` on an existing machine id

### LINKED ISSUE #369: v1.0.2 always shows changes - adds template_tags
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v1.3.1
on darwin_amd64
```

### Affected Resource(s)

- opennebula_virtual_machine

### Terraform Configuration Files

```hcl
resource "opennebula_virtual_machine" "server" {
  count          = var.vmcount
  name           = var.vmname
  cpu            = var.cpu
  vcpu           = var.vcpu
  memory         = var.memory
  group          = var.group
  permissions    = "660"
  on_disk_change = "recreate" # Tell Terraform to recreate the VM if the disk need to be updated

  # from here https://github.com/OpenNebula/terraform-provider-opennebula/blob/a6c428b07da88b89019b7dd374a343f5955e48b3/opennebula/resource_opennebula_virtual_machine_test.go#L793-L795
  cpumodel {
    model = "host-passthrough"
  }

  context = {
     <CUSTOM TAGS>
  }

  vmgroup {
    vmgroup_id = var.vmgroup_id
    role       = var.vmgroup_role
  }

  os {
    arch = "x86_64"
    boot = "disk0"
  }

  disk {
    image_id = var.image_id
    size     = var.disksize
    target   = "vda"
    driver   = "qcow2"
  }
  
  nic {
    network_id      = var.nicnetwork_id
    ip              = var.nicip
    security_groups = var.sgs
  }

  nic {
    network_id      = var.nicnetwork_id-2
    ip              = var.nicip-2
    security_groups = var.sgs-2
  }

  tags = {
    environment = var.tagsenv
  }

  graphics {
    type   = "VNC"
    listen = "0.0.0.0"
  }

  lifecycle {
    create_before_destroy = false
  }

}
```

### Debug Output

- After applying, the template_tags is in the state file with a null value

```
$ cat /tmp/terraform.tfstate | grep template_tags  | head -1
            "template_tags": null,
```

### Expected Behavior

- Plan shows the below:

```
No changes. Your infrastructure matches the configuration.
```

### Actual Behavior

- Plan always shows an addition of `template_tags` despite being in the state file with a null value

```
  # module.server["server"].opennebula_virtual_machine.server[0] will be updated in-place
  ~ resource "opennebula_virtual_machine" "server" {
        id             = "479"
        name           = "server"
        tags           = {
            "environment" = "stage"
        }
      + template_tags  = (known after apply)
        # (22 unchanged attributes hidden)

        # (7 unchanged blocks hidden)
    }
```

### Steps to Reproduce

- We are trying to upgrade from version `0.4.3` to `1.0.2`
- This behaviour was not present in provider version 0.4.3, a subsequent apply would show no changes.

### Important Factoids

- We are not using VM templates
- After destroying and applying, the state file shows a none null value and subsequent plan/apply show no changes
```
$ cat /tmp/terraform.tfstate | grep template_tags | head -1
            "template_tags": {},
```

### LINKED ISSUE #377: improve virtual machine import
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

TF: 1.3.6
Provider: 1.1.0-rc2

### Affected Resource(s)

- opennebula_virtual_machine

### Terraform Configuration Files

```hcl
resource "opennebula_virtual_machine" "test" {
}
```

### Expected Behavior

Some additional sections could be added, for instance importing a VM with `GRAPHICS` and `OS` sections on cloud side:
```
resource "opennebula_virtual_machine" "test" {
    cpu          = 1
    default_tags = {}
    gid          = 0
    gname        = "oneadmin"
    id           = "1"
    lcmstate     = 36
    memory       = 128
    name         = "Alpine Linux 3.14-1"
    permissions  = "600"
    state        = 3
    tags_all     = {}
    uid          = 0
    uname        = "oneadmin"
    vcpu         = -1

    graphics {
        listen = "0.0.0.0"
        port   = "5901"
        type   = "vnc"
    }

    os {
        arch = "x86_64"
    }

    timeouts {}
}
```

### Actual Behavior

```
# opennebula_virtual_machine.test:
resource "opennebula_virtual_machine" "test" {
    cpu          = 1
    default_tags = {}
    gid          = 0
    gname        = "oneadmin"
    id           = "0"
    lcmstate     = 0
    memory       = 128
    name         = "Alpine Linux 3.14-0"
    permissions  = "600"
    state        = 6
    tags_all     = {}
    uid          = 0
    uname        = "oneadmin"
    vcpu         = -1
    timeouts {}
}
```

### Steps to Reproduce

1. `terraform import opennebula_virtual_machine.test ID`
2. `terraform state show opennebula_virtual_machine.test`

### References

There is already import related issues but not necessarily on the same parts:
- #356 is about improving tags import and related acceptance tests
- #312 is about improving the default values imported

### PR DESCRIPTION
**Pull request by treywelsh**
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for PR followers and do not help prioritize the request

### Description

This PR remove the constraint that condition reading of some cloud side parts: `OS`, `GRAPHICS`, `CPU_MODEL`, `FEATURES`, `SCHED_REQUIREMENTS`, `SCHED_DS_REQUIREMENTS`, `DESCRIPTION`.
Until now they are read only when configured, this avoid diffs when the VM is instantiated from a template and then inherit attributes.
I didn't add any `Computed` behavior (may lead to a diff if there is some default configuration made on cloud side).
This should allow a bit more helpful import of the virtual machine resource.

I also added some basic reading code in order to have less null fields in state (related to #312 and #369 ):
Until now `template_id`, `template_disk`, `template_nic`, template_tags are filled at virtual machine creation when instantiating a VM from a template. After that they don't change because they reflect the template used at the VM creation.

I add some reading code to import the `template_id` (in the VM there is a `TEMPLATE_ID` that I may use), however the template content may have changed so I won't fill `template_disk` and `template_nic`, and `template_tags`.

### References

Close #377
Close #312 
Close #369 

### New or Affected Resource(s)

- opennebula_virtual_machine
- opennebula_virtual_router_instance

### Checklist

- [ ] I have created an issue and I have mentioned it in `References`
- [ ] My code follows the style guidelines of this project (use `go fmt`)
- [ ] My changes generate no new warnings or errors
- [ ] I have updated the unit tests and they pass succesfuly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation (if needed)
- [ ] I have updated the changelog file

### CODE REVIEW

**Comment by treywelsh** [comment]
Without one of these points, I won't consider importing `disk` or `nic` as a priority:

- consider to externalize `disk` and `nic` as resources (I proposed in the past via PR #318  #320 )
- SDK issues [mentionned in this comment](https://github.com/OpenNebula/terraform-provider-opennebula/pull/80#issuecomment-732308720) are fixed
- we consider a [migration from the SDK to the framework](https://developer.hashicorp.com/terraform/plugin/framework/migrating)

Actual disk/nic code management is a bit complex, a modification easily break something

**Comment by treywelsh** [comment]
Finally I may try to solve #369 as well in this PR

**Review by frousselet — APPROVED** [review]

**Comment by philipfreude** [comment]
This merge results for us in an issue in which terraform always tries to add template_section_names to each opennebula_virtual_machine. This happens on every terraform run.
e.g.
```
~ resource "opennebula_virtual_machine" "control_nodes" {
        id                     = "5558"
        name                   = "rke-control3.example.com"
      + template_section_names = (known after apply)
        # (25 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
```

**Comment by treywelsh** [comment]
It's a migration problem, you're updating the provider version from an older release to 1.1.1, and you created your virtual machine with the previous release.

`template_section_names` keep tracks of sections names inherited from a template, and then is read at VM creation step only.
When you apply for the first time with v1.1.1, terraform adds `"template_section_names": null,` in the state and then show the diff at each apply.

If your VM was created without any `template_id` edit the state to add the `template_section_names` line:
```
    {
      "mode": "managed",
      "type": "opennebula_virtual_machine",
...
        {
...
            "template_section": [],
            "template_section_names": {},
            "template_tags": {},
...
```

But if `template_id` is in use for the VM you have to add some content in it:
```
    {
      "mode": "managed",
      "type": "opennebula_virtual_machine",
...
        {
...
            "template_section": [],
            "template_section_names": {
                "GRAPHICS": "",
                "OS": "",
                ... 
            },
            "template_tags": {},
...
```
The content should be updated to contains all "vector" names ( i.e. for sections defined like this in OpenNebula template: `NAME = [ KEY = VALUE, ... ]` you have to add the `NAME`)

I you don't want to edit the state, I submitted #409

**Pull request merged**
