### PR TITLE
[resource][virtual_machine/template]: add DEV_PREFIX, CACHE, DISCARD, IO attributes to DISK section

### LINKED ISSUE #233: Template: Add FEATURES section and DEV_PREFIX attribute to DISK section
We have the use case to add the FEATURES section as well as add the DEV_PREFIX attribute to DISK section.
I created a branch https://github.com/peterloeffler/terraform-provider-opennebula/tree/add_features_section_and_dev_prefix_disk_attribute that seems to handle this.
Would it be ok to make a pull request here to get this into the master and in the next version?
Is there something to do it in a better way or to add?

Also looked into adding the attributes CACHE, DISCARD and IO to the DISK section but it seems like it's not available in the OpenNebula package.

### LINKED ISSUE #291: add disk attributes (DEV_PREFIX, CACHE, DISCARD, IO)
We need the following disk attributes for our production environment:
- DEV_PREFIX
- CACHE
- DISCARD
- IO

There is a pull request to implement this: https://github.com/OpenNebula/terraform-provider-opennebula/pull/242

### PR DESCRIPTION
**Pull request by peterloeffler**
I removed the default value (raw) for `volatile_format` because this attribute would be added any time when one wants to add any of the attributes. This then conflicts when there already is an `image_id`.

### CODE REVIEW

**Comment by treywelsh** [comment]
A bit of context:
This PR remove changes added by PR #240 pushed by @christian7007 
Related issue: #239

**Comment by peterloeffler** [comment]
> A bit of context: This PR remove changes added by PR #240 pushed by @christian7007 Related issue: #239

Hmm. I tested around a bit and for me it looks like with this default value the provider always adds the volatile_format attribute. That makes no sense because then we are not able to add any disks via image_id anymore.

**Comment by treywelsh** [comment]
I reopened #239 to investigate on the default `raw` value problem.
By the way I let the CI run on this PR to see if it works.

**Comment by treywelsh** [comment]
Raw default reverted by #257 (Alternative fix proposed in https://github.com/OpenNebula/terraform-provider-opennebula/pull/260) please rebase your work and remove this change from this PR

**Comment by peterloeffler** [comment]
Rebase done.
Checks on OpenNebula 6 seems to fail also on other pull requests due to some timeout issues.

**Comment by frousselet** [comment]
Hi @peterloeffler,

CI should be fixed on `master` now and tested with OpenNebula 6.4. Could you rebase once again please?

Thanks.

**Comment by frousselet** [comment]
Hi @peterloeffler,

CI should be fixed on `master` now and tested with OpenNebula 6.4. Could you rebase once again please?

Thanks.

**Comment by treywelsh** [comment]
Sorry for the time it takes to work on this PR, I want to give it a try when I'll have time.
For now `disk` and `nic` sections have over complex code to work properly (we'll probably make this evolve later), and then I prefer to give it some quick manual tries in addition to the CI tests.

Thank your for your involvement

**Review by treywelsh — APPROVED** [review]

**Comment by peterloeffler** [comment]
> Sorry for the time it takes to work on this PR, I want to give it a try when I'll have time. For now `disk` and `nic` sections have over complex code to work properly (we'll probably make this evolve later), and then I prefer to give it some quick manual tries in addition to the CI tests.
> 
> Thank your for your involvement

Do you have any estimation on when this could happen?
We would really need this feature for our production environment.
As well as https://github.com/OpenNebula/terraform-provider-opennebula/pull/272

**Comment by frousselet** [comment]
Hello Peter,

Could you open an issue for this pull request please? It will help us to prioritize your request.

Thanks

**Comment by treywelsh** [comment]
Could you rebase this PR a last time please ?

**Pull request closed without merging**
