### PR TITLE
Make update of "gateway" "dns" and "network_mask" possible.

### PR DESCRIPTION
**Pull request by puppetmaster**
Change "GATEWAY" "DNS" and "NETWORK_mask" parameters for virtual network on ONE
on gateway dns and network_mask update in terraform

### CODE REVIEW

**Comment by jaypif** [comment]
Hi @puppetmaster 

thank you! It looks really good.
Can you also add (or update) test case in `resource_opennebula_virtual_network_test.go` file ? 
This will improve coverage and also avoid possible non regression.

Thank you

**Comment by jaypif** [comment]
Hi @puppetmaster 

Thank you for adding test.
You also add new changes in the code not linked with the PR. 
I prefer to having 2 different PRS for both changes (comments and changes in resource_image.go are not linked with the network). Can you slit you changes into 2 different PR ?

Keep only stuff linked to network here (only 2 files should be changed) and create another PR for comments and other stuff you did in other files.

thank you

**Comment by puppetmaster** [comment]
It's only comments, no code change at all. And sorry I don't currently have the time to change this PR, maybe next week.

**Comment by puppetmaster** [comment]
The comment commit is reverted.

**Pull request merged**
