### PR TITLE
Migrating to the terraform plugin SDK.

### PR DESCRIPTION
**Pull request by lazzurs**
Migrated using the automated tool without any issues. Build runs as
expected.

### CODE REVIEW

**Comment by jaypif** [comment]
Hi @lazzurs 
Can you rebase your commit to the last master ? 
There is a conflict on a resource file and I did some update for CI.

Thank you

**Comment by lazzurs** [comment]
Rebase done and tests passing. Let me know if there is anything else you need.

**Comment by trenton42** [comment]
Is this still in progress? I would like to make some PRs, but it looks like I should wait for this to be merged first as it is quite a large change.

**Comment by lazzurs** [comment]
I would think it could do with updating to the latest plugin SDK and checking but it should be merged. 

@jaypif is this likely to get merged if I update it?

**Comment by treywelsh** [comment]
Hi @lazzurs,

Thank you for your work and sorry for the delay, I'm one of the contributors that work on best effort basis :)

I just found [this page](https://www.terraform.io/docs/extend/plugin-sdk.html#step-2-migrate) to help users migrate but I didn't read it yet.

Could you give some more details on the possible effects of this PR ?
I suppose that the SDK code continue to evolve but not the code we are using, could it break something ?
Do we need to heavily test it to be sure it won't broke anything (some test case may be not covered...) ?

**Comment by jaypif** [comment]
@lazzurs 

to complete @treywelsh answer, it could not be merged yet as the master branch evolved since December and there are conflicts with you commit.
Can you rebase it again (and sorry) ? 

Even if there are some other issue We are very interested in using the new SDK but we need to be sure it do not break existing basis.

I am freezing new merge in master until your PR is merged.

**Comment by treywelsh** [comment]
For reference, here is the tool to run to migrate: https://github.com/hashicorp/tf-sdk-migrator

**Comment by treywelsh** [comment]
This PR would require to resolve conflicts and is no more up to date (migrate to v1.1.0 version of the SDK).

I ran the migration script and opened this PR: #139 
It migrates the provider to the version v1.7.0 and is up to date

Thank you very much for the time spent on this PR

**Pull request closed without merging**
