### PR TITLE
F-447 F-448: externalize quotas as resources

### LINKED ISSUE #447: Add `opennebula_group_quota` resource
### Description

I am facing an issue where using `quotas` in `opennebula_group` applies only in one of our two zones, and detects drift when creating resources without defining a quota.

Instead of using an attribute, I suggest to add a new resource `opennebula_group_quota` to be able to select the zone where the quotas will apply.

In the HCL bellow, all `opennebula_group_quota` > `scope` conflict with each others.

`units`, `running_units`, `size`, `running_size`, `leases` are optional. If not set, the value is `-1`, meaning `∞`.

Since a quota doesn't have any ID in the OpenNebula side, there is no way to import. Even if the quota exists, terraforming a new one will override it.

In the same way, there is no data source, but quotas might be returned when fetching `opennebula_group` as usual.

### New or affected resources and data sources

- `opennebula_group`
- `opennebula_group_quotas`

### Potential terraform configuration

```HCL
resource "opennebula_group" "hw" {
  name = "My Group"

  # quotas {} # Deprecated
}

resource "opennebula_group_quota" "vm" {
  group_id = opennebula_group.hw.id
  
  scope         = "vm"
  units         = 8    # Number of units
  running_units = 8    # Number of running units
}

resource "opennebula_group_quota" "cpu" {
  group_id = opennebula_group.hw.id
  
  scope         = "cpu"
  units         = 16    # Number of units
  running_units = 16    # Number of running units
}

resource "opennebula_group_quota" "memory" {
  group_id = opennebula_group.hw.id
  
  scope        = "memory"
  size         = 16384  # Total size in MB
  running_size = 16384  # Size of running memory in MB
}

resource "opennebula_group_quota" "system_disks" {
  group_id = opennebula_group.hw.id
  
  scope = "system_disks"
  size  = 20480          # Size in MB
}

resource "opennebula_group_quota" "image" {
  group_id = opennebula_group.hw.id
  

  scope    = "image"
  image_id = 100          # Only if scope=image
  units    = 2            # Number of units
}

resource "opennebula_group_quota" "network" {
  group_id = opennebula_group.hw.id
  
  scope    = "network"
  leases   = 1            # Number of units
}

resource "opennebula_group_quota" "datastore" {
  group_id = opennebula_group.hw.id
  
  scope        = "datastore"
  datastore_id = 100          # Only if scope=datastore
  units        = 1            # Number of units
  size         = 10240        # Size in MB. Only available if scope=datastore
}
```

### References

#448

### LINKED ISSUE #448: Add `opennebula_user_quota` resource
### Description

I am facing an issue where using `quotas` in `opennebula_user` applies only in one of our two zones, and detects drift when creating resources without defining a quota.

Instead of using an attribute, I suggest to add a new resource `opennebula_user_quota` to be able to select the zone where the quotas will apply.

In the HCL bellow, all `opennebula_user_quota` > `scope` conflict with each others.

`units`, `running_units`, `size`, `running_size`, `leases` are optional. If not set, the value is `-1`, meaning `∞`.

Since a quota doesn't have any ID in the OpenNebula side, there is no way to import. Even if the quota exists, terraforming a new one will override it.

In the same way, there is no data source, but quotas might be returned when fetching `opennebula_user` as usual.

### New or affected resources and data sources

- `opennebula_user`
- `opennebula_user_quotas`

### Potential terraform configuration

```HCL
resource "opennebula_user" "hw" {
  name = "My User"

  # quotas {} # Deprecated
}

resource "opennebula_user_quota" "vm" {
  user_id = opennebula_user.hw.id
  
  scope         = "vm"
  units         = 8    # Number of units
  running_units = 8    # Number of running units
}

resource "opennebula_user_quota" "cpu" {
  user_id = opennebula_user.hw.id
  
  scope         = "cpu"
  units         = 16    # Number of units
  running_units = 16    # Number of running units
}

resource "opennebula_user_quota" "memory" {
  user_id = opennebula_user.hw.id
  
  scope        = "memory"
  size         = 16384     # Size in MB
  running_size = 16384     # Size of running memory in MB
}

resource "opennebula_user_quota" "system_disks" {
  user_id = opennebula_user.hw.id
  
  scope         = "system_disks"
  size         = 20480            # Size in MB
}

resource "opennebula_user_quota" "image" {
  user_id = opennebula_user.hw.id
  

  scope    = "image"
  image_id = 100          # Only if scope=image
  units    = 2            # Number of units
}

resource "opennebula_user_quota" "network" {
  user_id = opennebula_user.hw.id
  
  scope    = "network"
  units    = 1            # Number of units
}

resource "opennebula_user_quota" "datastore" {
  user_id = opennebula_user.hw.id
  
  scope        = "datastore"
  datastore_id = 100          # Only if scope=datastore
  units        = 1            # Number of units
  size         = 10240        # Size in MB. Only available if scope=datastore
}
```

### References

#447

### PR DESCRIPTION
**Pull request by treywelsh**
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for PR followers and do not help prioritize the request

### Description

Until now quotas are only a schema part (via some nested typeset and typelists) of the users ans group resources, this PR externalize quotas in their own resource.
One resource for the users, another for the groups.

After some tests it's possible to define several quota resource for a single user or a signle group.

### References

Close #447
Close #448

### New or Affected Resource(s)

- opennebula_group
- opennebula_group_quotas
- opennebula_user
- opennebula_user_quotas

### Checklist

- [ ] I have created an issue and I have mentioned it in `References`
- [ ] My code follows the style guidelines of this project (use `go fmt`)
- [ ] My changes generate no new warnings or errors
- [ ] I have updated the unit tests and they pass succesfuly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation (if needed)
- [ ] I have updated the changelog file

### CODE REVIEW

**Review by frousselet — CHANGES_REQUESTED** [review]
Should be `opennebula_[user|group]_quota` instead of `opennebula_[user|group]_quotas` since the resource manage only one quota.

**Comment by treywelsh** [comment]
For this first shot this PR didn't followed the schema shown in the issues #447 and #448
This works like this:
```hcl
resource "opennebula_user" "example" {
  name          = "test"
  password      = "test2"
  auth_driver   = "core"

  lifecycle {
    ignore_changes = [
      "quotas"
    ]
  }
}

resource "opennebula_user_quotas" "test" {
    user_id = opennebula_user.example.id
    datastore {
      id     = 1
      images = 5
      size   = 10000
    }
    vm{
      cpu            = 3
      running_cpu    = 3
      memory         = 2048
      running_memory = 2048
    }
    network {
      id     = 10
      leases = 6
    }
    network {
      id     = 11
      leases = 4
    }
    image {
      id          = 8
      running_vms = 1
    }
    image {
      id          = 9
      running_vms = 1
    }
}
```
It was easier to migrate as a resource, it's easier to import via terraform import and overall it require a bit less of text.
I'm able to split the quotas resource to only apply a quota to a given type of resource (image or network or datastore or VM) but it seems to me that we'll at least loose the capability to easily import the quotas (I'll need to find a way to make the provider  read partially the quotas).

**Comment by frousselet** [comment]
Understood. I'll test, but are we not going to fall back into the same situation?
It might solve the zone issue, but not the drift one.

> and detects drift when creating resources without defining a quota

**Comment by treywelsh** [comment]
I'm not sure I got was the drift problem was, or maybe I forgot, so ok blame on me. 
Not sure the drift problem is still there so If we/you can test it again it would be nice.

By the way I need to check via #458 if I can't improve the quota import because I said it was a problem in my previous comment

**Comment by treywelsh** [comment]
I'm finally able to propose something close to the schema of the issue:
```terraform
resource "opennebula_user" "example" {
  name          = "test"
  password      = "test2"
  auth_driver   = "core"

  lifecycle {
    ignore_changes = [
      "quotas"
    ]
  }
}

resource "opennebula_user_quotas" "example_datastore" {
  user_id = opennebula_user.example.id
  datastore {
    id     = 1
    images = 3
    size   = 10000
  }
}

resource "opennebula_user_quotas" "example_image" {
  user_id = opennebula_user.example.id
  image {
    id          = 8
    running_vms = 1
  }
}

resource "opennebula_user_quotas" "example_vm" {
  user_id = opennebula_user.example.id
    vm{
      cpu            = 3
      running_cpu    = 3
      memory         = 2048
      running_memory = 2048
    }
}

resource "opennebula_user_quotas" "example_net" {
  user_id = opennebula_user.example.id
  network {
    id     = 10
    leases = 6
  }
  network {
    id     = 11
    leases = 4
  }
}
```
Tradeoffs:
There's a `ConflictWith` behavior between the sections of the quotas so we must split the quotas across several resources.
And in order to import a resource we need to do something like:
```
terraform import opennebula_group_quotas.example 123:image
```
Where `123` is the group ID, and `image` is the type of the quota we are trying to import.
All these last changes were added in the last commit of my branch so it's easy to test both variants and choose

**Review by frousselet — APPROVED** [review]

**Pull request merged**
