### PR TITLE
only set randompasswd in graphics template if it's true

### PR DESCRIPTION
**Pull request by nilsding**
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for PR followers and do not help prioritize the request

### Description

older OpenNebula versions (like 5.12) interpret the `RANDOM_PASSWORD` as truthy if its value is not empty and therefore try to generate a password, which when using VNC will be too long and not truncated due to another bug that's already been fixed in the latest release.

(yes, I know, we should really update our setup ...)

### New or Affected Resource(s)

- opennebula_template

### Checklist

- [ ] I have created an issue and I have mentioned it in `References`
- [x] My code follows the style guidelines of this project (use `go fmt`)
- [x] My changes generate no new warnings or errors
- [x] I have updated the unit tests and they pass succesfuly
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the documentation (if needed)
- [ ] I have updated the changelog file

### CODE REVIEW

**Comment by frousselet** [comment]
Hello @nilsding,

Unfortunately we don't support OpenNebula bellow `5.12`.
I would suggest you to fork the provider while you are on a version bellow `5.12` and [compile](https://github.com/OpenNebula/terraform-provider-opennebula/blob/master/CONTRIBUTING.md#building-from-sources) your version including your changes on your side.

**Comment by nilsding** [comment]
Hi @frousselet, the readme mentions that OpenNebula `~> 5.12` is still supported 🤔 

But the bug fixed by this PR also affects at least `>= 6.0, < 6.1.80`, as the `random_password` handling was changed around that time in https://github.com/OpenNebula/one/commit/0edcc7a7baa0d318671fa27731830e7d4775390d

**Comment by frousselet** [comment]
My bad, I misread 😬
I reopen it

**Comment by akurz** [comment]
Hi @frousselet, looks like this PR was "forgotten" - would you be so kind and reopen it, thx!

**Comment by treywelsh** [comment]
hi, sorry for the late reply, instead of modifying the default behavior for all the releases, could you check the version instead and add an if - else to handle your specific case ?

Here's an example: https://github.com/OpenNebula/terraform-provider-opennebula/blob/master/opennebula/resource_opennebula_marketplace_app.go#L180

Then rebase your PR, add a line in the CHANGELOG and I'll review it

**Comment by treywelsh** [comment]
I remove the stale label to let it open some more days as it took me a bit of time to review it

**Comment by dgarcia18** [comment]
Tested for OpenNebula versions >5.12. For these versions, setting RANDOM_PASSWD = "NO" is completely equivalent to not setting it. LGTM, merging.

**Review by dgarcia18 — APPROVED** [review]

**Pull request merged**
