### PR TITLE
B-220: template: fix template update

### LINKED ISSUE #220: [resource][template] template update
For a template resource it's possible to add a new key, to update an existing key, but it's not possible to remove a key. This is easily visible playing with the content of the `tags` section.

This problem has been identified in #218 

Note: in case it helps, the VM `user_template` section management has been reworked in #206

### PR DESCRIPTION
**Pull request by treywelsh**
The template resource has some faulty update code in `resourceOpennebulaTemplateUpdate`:
```
	if d.HasChange("tags") {
		tagsInterface := d.Get("tags").(map[string]interface{})
		for k, v := range tagsInterface {
			tpl.Template.Del(strings.ToUpper(k))
			tpl.Template.AddPair(strings.ToUpper(k), v.(string))
		}

		err = tc.Update(tpl.Template.String(), 1)
		if err != nil {
			return err
		}
	}
```
if a key is removed, the key won't be listed anymore in `tagsInterface`, then there will be no loop iteration for the key we want to remove.
In addition, I think that to remove a key there is no other way than use the "replace" behavior of the template update method.
Look at [XML-RPC API for details](https://docs.opennebula.io/5.12/integration/system_interfaces/api.html#one-template-update)

We need to do something similar that I did in VM template part using `GetChange` method in #206 
The goal is to detect when a key is added/removed/updated and adapt the behavior.

Close #220

### CODE REVIEW

**Comment by treywelsh** [comment]
I need to update this PR to fix the escapment problem with:
```
sched_requirements = "CLUSTER_ID!=\\\"123\\\""
```

**Comment by treywelsh** [comment]
I reworked the template management in the same way I did for the VM in #206

**Review by jaypif — CHANGES_REQUESTED** [review]
Some use cases are not tested. Please add them to improve coverage

**Comment by treywelsh** [comment]
I made this PR evolve to fix some related problems:
- VM and template resources: some attributes added by #154 weren't read for the VM resource: flattening was done on the`Template` section, but attributes were in `UserTemplate` section.
  This required to split a flattening method shared by VM and template resources in two methods.
- VM and Template resources: escapment of double quotes has been added on `sched_requirements` and `sched_ds_requirements` in update methods.
- tests added

However we can't test the deletions of `sched_requirements` and `sched_ds_requirements` attributes....

**Review by jaypif — APPROVED** [review]

**Pull request merged**
